# Generated by Django 4.2 on 2023-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='saveimage',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
