# Generated by Django 4.2 on 2023-04-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0003_saveimage_name_alter_saveimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveimage',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
