# Generated by Django 4.2 on 2023-04-27 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0004_alter_saveimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveimage',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saveimage',
            name='read_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 3, 39, 35, 261833, tzinfo=datetime.timezone.utc)),
        ),
    ]
