# Generated by Django 4.2 on 2023-04-27 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0005_saveimage_count_saveimage_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveimage',
            name='read_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
