# Generated by Django 4.2 on 2023-04-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0006_alter_saveimage_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveimage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
