# Generated by Django 4.2 on 2023-04-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0007_alter_saveimage_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitTrace',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=255)),
                ('useragent', models.CharField(max_length=255)),
                ('referer', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='saveimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='saveimage',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
