# Generated by Django 4.2 on 2023-04-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0008_visittrace_remove_saveimage_id_alter_saveimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittrace',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visittrace',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
